name: Code check

env:
  NODE_VERSION: 22
  PNPM_VERSION: 10.7.1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_code:
    name: Run type checking, linting, and testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: List files
        run: ls -alt

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Check build
        run: pnpm build

      - name: Run smoke tests
        run: pnpm test:smoke

  notify:
    name: Send Slack notification on failure
    needs: check_code
    # Run this job only if the previous job failed and the event was triggered by the 'AdguardTeam/ecsstree' repository
    # Note: 'always()' is needed to run the notify job even if the test job was failed
    if:
      ${{
        always() &&
        needs.check_code.result == 'failure' &&
        github.repository == 'AdguardTeam/ecsstree' &&
        (
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: workflow, repo, message, commit, author, eventName, ref, job
          job_name: check_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
