name: Publish release

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:
    inputs:
      ref:
        description: Ref to publish manually
        required: false
        type: string

jobs:
  publish:
    uses: AdGuardSoftwareLimited/ext-shared-actions/.github/workflows/publish-release.yml@master
    with:
      package_file: ecsstree.tgz
      npm_package_name: "@adguard/ecss-tree"
      target_repo: AdguardTeam/ecsstree
      ref: ${{ inputs.ref }}
    secrets: inherit
